[package]
name = "bpf-ring-buffer"
version = "0.1.0"
authors = ["Vladislav Melnik <vladislav.melnik@viablesystems.io>"]
edition = "2021"
rust-version = "1.58.1"
license = "MIT"

[dependencies]
libc = { workspace = true }
log = { workspace = true }
epoll = { workspace = true }